name: pypsa-eur-macos
channels:
  - bioconda
  - plotly
  - gurobi
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0=py_0
  - appdirs=1.4.4=py_0
  - appnope=0.1.2=py37hecd8cb5_1001
  - atlite=0.0.3=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=mkl
  - blosc=1.16.3=hd9629dc_0
  - bokeh=2.3.0=py37hecd8cb5_0
  - bottleneck=1.3.2=py37hf1fa96c_1
  - brotlipy=0.7.0=py37h9ed2024_1003
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2021.1.19=hecd8cb5_1
  - cairo=1.16.0=h8023c5d_1
  - cartopy=0.18.0=py37hc4b8d57_0
  - certifi=2020.12.5=py37hecd8cb5_0
  - cffi=1.14.5=py37h2125817_0
  - cfitsio=3.470=hb33e7b4_2
  - cftime=1.4.1=py37he3068b8_0
  - chardet=4.0.0=py37hecd8cb5_1003
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=py37hecd8cb5_0
  - cloudpickle=1.6.0=py_0
  - conda=4.10.0=py37hecd8cb5_0
  - conda-package-handling=1.7.2=py37h22f3db7_0
  - configargparse=1.2.3=py_0
  - cryptography=3.3.1=py37hbcfaee0_1
  - curl=7.67.0=ha441bb4_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37haf1e3a3_0
  - dask=2020.12.0=pyhd3eb1b0_0
  - dask-core=2020.12.0=pyhd3eb1b0_0
  - datrie=0.8.2=py37h9ed2024_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - dill=0.3.3=pyhd3eb1b0_0
  - distributed=2021.3.0=py37hecd8cb5_0
  - docutils=0.16=py37_1
  - entsoe-py=0.2.10=py_0
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.10=hb1e8313_2
  - fiona=1.8.13.post1=py37h9c05f0f_0
  - fontconfig=2.13.1=ha9ee91d_0
  - freetype=2.10.4=ha233b18_0
  - freexl=1.0.6=h9ed2024_0
  - fsspec=0.8.3=py_0
  - gdal=3.0.2=py37hbe65578_0
  - geographiclib=1.50=py_0
  - geopandas=0.8.1=py_0
  - geopy=2.1.0=pyhd3deb0d_0
  - geos=3.8.0=hb1e8313_0
  - geotiff=1.5.1=h0b0f252_0
  - gettext=0.19.8.1=hb0f4f8b_2
  - giflib=5.1.4=h1de35cc_1
  - gitdb=4.0.5=py_0
  - gitpython=3.1.12=pyhd3eb1b0_1
  - glib=2.67.4=hdf23fa2_1
  - gurobi=9.1.1=py37_0
  - hdf4=4.2.13=h39711bb_2
  - hdf5=1.10.4=hfa1e0ec_0
  - heapdict=1.0.1=py_0
  - icu=58.2=h0a44026_3
  - idna=2.10=pyhd3eb1b0_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2019.4=233
  - ipython=7.20.0=py37he01cfaa_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - iso3166=1.0.1=pyh9f0ad1d_0
  - jdcal=1.4.1=py_0
  - jedi=0.18.0=py37hecd8cb5_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=he5867d9_2
  - json-c=0.13.1=h3efe00b_0
  - jsonschema=3.2.0=py_2
  - jupyter_core=4.7.1=py37hecd8cb5_0
  - kealib=1.4.7=hf5ed860_6
  - kiwisolver=1.3.1=py37h23ab428_0
  - krb5=1.16.4=hddcf347_0
  - lcms2=2.11=h92f6f08_0
  - libboost=1.67.0=hebc422b_4
  - libcurl=7.67.0=h051b688_0
  - libcxx=10.0.0=1
  - libdap4=3.19.1=h3d3e54a_0
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - libgdal=3.0.2=h42cfeda_0
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libkml=1.3.0=hbe12b63_4
  - libnetcdf=4.6.1=hd5207e6_2
  - libpng=1.6.37=ha441bb4_0
  - libpq=11.5=h31a01ba_2
  - libsolv=0.7.14=hd174df1_4
  - libspatialindex=1.9.3=h0a44026_0
  - libspatialite=4.3.0a=h5142b36_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_0
  - libxml2=2.9.10=h7cdb67c_3
  - libxslt=1.1.34=h83b36ba_0
  - llvm-openmp=10.0.0=h28b9765_0
  - locket=0.2.1=py37hecd8cb5_1
  - lxml=4.6.2=py37h26b266a_0
  - lz4-c=1.8.1.2=h1de35cc_0
  - lzo=2.10=haf1e3a3_2
  - mamba=0.1.2=py37ha1cc60f_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.3.4=py37hecd8cb5_0
  - matplotlib-base=3.3.4=py37h8b3ea08_0
  - memory_profiler=0.58.0=py_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37h9ed2024_0
  - mkl_fft=1.3.0=py37ha059aab_0
  - mkl_random=1.1.1=py37h959d312_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.7.0=pyhd3eb1b0_0
  - msgpack-python=1.0.2=py37hf7b0b51_1
  - multiprocess=0.70.11.1=py37hf967b71_1
  - munch=2.5.0=py_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.2=h0a44026_1
  - netcdf4=1.4.2=py37h13743db_0
  - networkx=2.5=py_0
  - nose=1.3.7=pyhd3eb1b0_1006
  - numexpr=2.7.3=py37h16bde0e_0
  - numpy=1.18.5=py37h1da2735_0
  - numpy-base=1.18.5=py37h3304bdc_0
  - olefile=0.46=py37_0
  - openjpeg=2.3.0=hb95cd4c_1
  - openpyxl=3.0.6=pyhd3eb1b0_0
  - openssl=1.1.1k=h9ed2024_0
  - owslib=0.23.0=pyhd3eb1b0_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=1.2.3=py37hb2f4e1b_0
  - parso=0.8.1=pyhd3eb1b0_0
  - partd=1.1.0=py_0
  - pcre=8.44=hb1e8313_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.1.2=py37h5270095_0
  - pip=20.3.3=py37hecd8cb5_0
  - pixman=0.40.0=haf1e3a3_0
  - plotly=4.14.3=pyhd3eb1b0_0
  - plotly-orca=1.3.1=1
  - pluggy=0.13.1=py37_0
  - ply=3.11=py37_0
  - poppler=0.65.0=ha097c24_1
  - poppler-data=0.4.10=hecd8cb5_0
  - postgresql=11.5=h26bc10f_2
  - powerplantmatching=0.4.8=pyhd8ed1ab_0
  - progressbar2=3.37.1=py37_0
  - proj=6.2.1=hfd5b9e3_0
  - prompt-toolkit=3.0.8=py_0
  - psutil=5.8.0=py37h9ed2024_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pulp=1.6.8=py37_1000
  - py=1.10.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py37h9ed2024_0
  - pycountry=20.7.3=pyh9f0ad1d_0
  - pycparser=2.20=py_2
  - pyepsg=0.4.0=py37_0
  - pygments=2.8.1=pyhd3eb1b0_0
  - pykdtree=1.3.4=py37he3068b8_1002
  - pyomo=5.7=py37h4b3a949_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyproj=2.6.1.post1=py37hdfdfadc_1
  - pypsa=0.17.1=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37haf1e3a3_0
  - pyshp=2.1.2=py_0
  - pysocks=1.7.1=py37hecd8cb5_0
  - pytables=3.6.1=py37h5bccee9_0
  - pytest=6.2.2=py37hecd8cb5_2
  - pytest-runner=5.3.0=pyhd3eb1b0_0
  - python=3.7.9=h26836e1_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-utils=2.5.6=py37hecd8cb5_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd3eb1b0_0
  - pyutilib=6.0.0=py_1
  - pyyaml=5.3.1=py37haf1e3a3_1
  - rasterio=1.1.0=py37heeaa653_0
  - ratelimiter=1.2.0=py_1002
  - readline=8.1=h9ed2024_0
  - requests=2.25.1=pyhd3eb1b0_0
  - retrying=1.3.3=py37_2
  - rtree=0.9.4=py37_1
  - ruamel_yaml=0.15.87=py37haf1e3a3_1
  - scikit-learn=0.23.2=py37h959d312_0
  - scipy=1.6.1=py37h2515648_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - setuptools=52.0.0=py37hecd8cb5_0
  - shapely=1.7.1=py37hb435bde_0
  - six=1.15.0=py37hecd8cb5_0
  - smmap=4.0.0=pyhd3eb1b0_0
  - snakemake-minimal=5.24.2=py_0
  - snappy=1.1.8=hb1e8313_0
  - snuggs=1.4.7=py_0
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - soupsieve=2.2=pyhd3eb1b0_0
  - sqlite=3.33.0=hffcf06c_0
  - tbb=2018.0.5=h04f5b5a_0
  - tblib=1.7.0=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tiledb=1.6.3=h29f752d_0
  - tk=8.6.10=hb0a8c7a_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=py_0
  - toposort=1.6=pyhd8ed1ab_0
  - tornado=6.1=py37h9ed2024_0
  - tqdm=4.56.0=pyhd3eb1b0_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - tzcode=2020f=h35c211d_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - wrapt=1.12.1=py37h1de35cc_1
  - xarray=0.16.2=pyhd3eb1b0_0
  - xerces-c=3.2.3=h48eee30_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - yaml=0.2.5=haf1e3a3_0
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - argon2-cffi==20.1.0
    - astroid==2.4.2
    - async-generator==1.10
    - bleach==3.2.2
    - cdsapi==0.4.0
    - countrycode==0.2
    - defusedxml==0.6.0
    - descartes==1.1.0
    - entrypoints==0.3
    - git+https://github.com/PyPSA/glaes.git#egg=glaes
    - git+https://github.com/PyPSA/geokit.git#egg=geokit
    - ipykernel==5.4.3
    - isort==5.7.0
    - jupyter-client==6.1.11
    - jupyterlab-pygments==0.1.2
    - lazy-object-proxy==1.4.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nest-asyncio==1.4.3
    - notebook==6.2.0
    - pandocfilters==1.4.3
    - prometheus-client==0.9.0
    - pylint==2.6.0
    - pyzmq==21.0.0
    - send2trash==1.5.0
    - terminado==0.9.2
    - testpath==0.4.4
    - typed-ast==1.4.2
    - vresutils==0.3.1
    - webencodings==0.5.1
prefix: /Users/au518895/anaconda3/envs/pypsa-eur
